Current time: 2025-02-26 18:12:28.141697+00:00, Target time: 2025-02-26 19:12:28.141697+00:00
Found 0 sessions matching condition.
Notifications sent!
Current time: 2025-02-26 18:14:00.666733+00:00, Target time: 2025-02-26 19:14:00.666733+00:00
Found 0 sessions matching condition.
Notifications sent!
Current time: 2025-02-26 18:17:21.197539+00:00, Target time: 2025-02-26 19:17:21.197539+00:00
Found 1 sessions matching condition.
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\management\commands\send_notifications.py", line 12, in handle
    send_voting_session_notifications()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\tasks.py", line 34, in send_voting_session_notifications
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipients)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-43aba5395c6sm29649885e9.18 - gsmtp')
Current time: 2025-02-26 18:22:22.365026+00:00, Target time: 2025-02-26 19:22:22.365026+00:00
Found 0 sessions matching condition.
Notifications sent!
Current time: 2025-02-26 18:27:19.930723+00:00, Target time: 2025-02-26 19:27:19.930723+00:00
Found 0 sessions matching condition.
Notifications sent!
Task started
Sending notifications...
Task completed successfully
Current time: 2025-02-26 18:31:04.326768+00:00, Target time: 2025-02-26 19:31:04.326768+00:00
Found 0 sessions matching condition.
Notifications sent!
Task started
Sending notifications...
Task completed successfully
Current time: 2025-02-26 18:32:02.875131+00:00, Target time: 2025-02-26 19:32:02.875131+00:00
Found 0 sessions matching condition.
Notifications sent!
Task started
Sending notifications...
Task completed successfully
Current time: 2025-02-26 18:32:22.118015+00:00, Target time: 2025-02-26 19:32:22.118015+00:00
Found 0 sessions matching condition.
Notifications sent!
Task started
Sending notifications...
Task completed successfully
Current time: 2025-02-26 18:37:20.916881+00:00, Target time: 2025-02-26 19:37:20.916881+00:00
Found 0 sessions matching condition.
Notifications sent!
Task started
Sending notifications...
Task completed successfully
Current time: 2025-02-26 18:42:22.893343+00:00, Target time: 2025-02-26 19:42:22.893343+00:00
Found 0 sessions matching condition.
Notifications sent!
Task started
Sending notifications...
Task completed successfully
Current time: 2025-02-26 18:45:56.548640+00:00, Target time: 2025-02-26 19:45:56.548640+00:00
Found 0 sessions matching condition.
Notifications sent!
Task started
Sending notifications...
Task completed successfully
Current time: 2025-02-26 18:47:21.107587+00:00, Target time: 2025-02-26 19:47:21.107587+00:00
Found 0 sessions matching condition.
Notifications sent!
Task started
Sending notifications...
Task completed successfully
Current time: 2025-02-26 18:50:34.662248+00:00, Target time: 2025-02-26 19:50:34.662248+00:00
Found 0 sessions matching condition.
Notifications sent!
Task started
Sending notifications...
Task completed successfully
Current time: 2025-02-26 18:52:20.680821+00:00, Target time: 2025-02-26 19:52:20.680821+00:00
Found 0 sessions matching condition.
Notifications sent!
Task started
Sending notifications...
Task completed successfully
Current time: 2025-02-26 18:57:23.075254+00:00, Target time: 2025-02-26 19:57:23.075254+00:00
Found 0 sessions matching condition.
Notifications sent!
Task started
Sending notifications...
Task completed successfully
Current time: 2025-02-26 19:02:43.640290+00:00, Target time: 2025-02-26 20:02:43.640290+00:00
Found 0 sessions matching condition.
Notifications sent!
Task started
Sending notifications...
Task completed successfully
Current time: 2025-02-26 19:07:19.074350+00:00, Target time: 2025-02-26 20:07:19.074350+00:00
Found 0 sessions matching condition.
Notifications sent!
Task started
Sending notifications...
Task completed successfully
Current time: 2025-02-26 19:12:21.126534+00:00, Target time: 2025-02-26 20:12:21.126534+00:00
Found 0 sessions matching condition.
Notifications sent!
Task started
Sending notifications...
Task completed successfully
Current time: 2025-02-26 19:17:18.968330+00:00, Target time: 2025-02-26 20:17:18.968330+00:00
Found 0 sessions matching condition.
Notifications sent!
Task started
Sending notifications...
Task completed successfully
Current time: 2025-02-26 19:22:19.392409+00:00, Target time: 2025-02-26 20:22:19.392409+00:00
Found 0 sessions matching condition.
Notifications sent!
Task started
Sending notifications...
Task completed successfully
Current time: 2025-02-26 19:27:18.985037+00:00, Target time: 2025-02-26 20:27:18.985037+00:00
Found 0 sessions matching condition.
Notifications sent!
Task started
Sending notifications...
Task completed successfully
Current time: 2025-02-26 19:32:18.971500+00:00, Target time: 2025-02-26 20:32:18.971500+00:00
Found 0 sessions matching condition.
Notifications sent!
Task started
Sending notifications...
Task completed successfully
Current time: 2025-02-26 19:37:20.812111+00:00, Target time: 2025-02-26 20:37:20.812111+00:00
Found 0 sessions matching condition.
Notifications sent!
Task started
Sending notifications...
Task completed successfully
Current time: 2025-02-26 19:42:24.135548+00:00, Target time: 2025-02-26 20:42:24.135548+00:00
Found 0 sessions matching condition.
Notifications sent!
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 19:47:20.281693+00:00, Target time: 2025-02-26 20:47:20.281693+00:00
Found 0 sessions matching condition.
\u2705 Notifications sent successfully!
Notifications sent!
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 19:52:19.781225+00:00, Target time: 2025-02-26 20:52:19.781225+00:00
Found 0 sessions matching condition.
\u2705 Notifications sent successfully!
Notifications sent!
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 19:53:52.432926+00:00, Target time: 2025-02-26 20:53:52.432926+00:00
Found 1 sessions matching condition.
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\management\commands\send_notifications.py", line 26, in handle
    send_voting_session_notifications()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\tasks.py", line 34, in send_voting_session_notifications
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipients)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-43aba5710ebsm33592525e9.26 - gsmtp')
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 19:57:19.866644+00:00, Target time: 2025-02-26 20:57:19.866644+00:00
Found 1 sessions matching condition.
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\management\commands\send_notifications.py", line 26, in handle
    send_voting_session_notifications()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\tasks.py", line 34, in send_voting_session_notifications
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipients)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-43ab37403cfsm53185855e9.1 - gsmtp')
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 20:02:20.326592+00:00, Target time: 2025-02-26 21:02:20.326592+00:00
Found 0 sessions matching condition.
\u2705 Notifications sent successfully!
Notifications sent!
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 20:07:21.896498+00:00, Target time: 2025-02-26 21:07:21.896498+00:00
Found 0 sessions matching condition.
\u2705 Notifications sent successfully!
Notifications sent!
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 20:12:20.467621+00:00, Target time: 2025-02-26 21:12:20.467621+00:00
Found 0 sessions matching condition.
\u2705 Notifications sent successfully!
Notifications sent!
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 20:17:20.889067+00:00, Target time: 2025-02-26 21:17:20.889067+00:00
Found 0 sessions matching condition.
\u2705 Notifications sent successfully!
Notifications sent!
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 20:20:20.394359+00:00, Target time: 2025-02-26 21:20:20.394359+00:00
Found 1 sessions matching condition.
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\management\commands\send_notifications.py", line 26, in handle
    send_voting_session_notifications()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\tasks.py", line 34, in send_voting_session_notifications
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipients)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-390cd8e71c0sm6597732f8f.78 - gsmtp')
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 20:22:19.456170+00:00, Target time: 2025-02-26 21:22:19.456170+00:00
Found 1 sessions matching condition.
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\management\commands\send_notifications.py", line 26, in handle
    send_voting_session_notifications()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\tasks.py", line 34, in send_voting_session_notifications
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipients)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-390cd8e7114sm6698324f8f.74 - gsmtp')
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 20:27:19.610190+00:00, Target time: 2025-02-26 21:27:19.610190+00:00
Found 1 sessions matching condition.
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\management\commands\send_notifications.py", line 26, in handle
    send_voting_session_notifications()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\tasks.py", line 34, in send_voting_session_notifications
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipients)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-390cd8fbef5sm6949658f8f.90 - gsmtp')
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 20:32:19.586544+00:00, Target time: 2025-02-26 21:32:19.586544+00:00
Found 1 sessions matching condition.
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\management\commands\send_notifications.py", line 26, in handle
    send_voting_session_notifications()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\tasks.py", line 34, in send_voting_session_notifications
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipients)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-43aba5711dfsm32828385e9.27 - gsmtp')
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 20:37:19.132272+00:00, Target time: 2025-02-26 21:37:19.132272+00:00
Found 1 sessions matching condition.
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\management\commands\send_notifications.py", line 26, in handle
    send_voting_session_notifications()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\tasks.py", line 34, in send_voting_session_notifications
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipients)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-43b73718e2asm863125e9.21 - gsmtp')
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 20:42:21.664762+00:00, Target time: 2025-02-26 21:42:21.664762+00:00
Found 1 sessions matching condition.
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\management\commands\send_notifications.py", line 26, in handle
    send_voting_session_notifications()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\tasks.py", line 34, in send_voting_session_notifications
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipients)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-390dfbabc7csm1294765f8f.5 - gsmtp')
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 20:44:43.233322+00:00, Target time: 2025-02-26 21:44:43.233322+00:00
Found 1 sessions matching condition.
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\management\commands\send_notifications.py", line 26, in handle
    send_voting_session_notifications()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\tasks.py", line 34, in send_voting_session_notifications
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipients)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-43b7371701esm996355e9.17 - gsmtp')
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 20:47:22.832367+00:00, Target time: 2025-02-26 21:47:22.832367+00:00
Found 1 sessions matching condition.
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\management\commands\send_notifications.py", line 26, in handle
    send_voting_session_notifications()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\tasks.py", line 34, in send_voting_session_notifications
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipients)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-43b8d6bc417sm52345e9.0 - gsmtp')
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 20:52:19.642047+00:00, Target time: 2025-02-26 21:52:19.642047+00:00
Found 1 sessions matching condition.
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\management\commands\send_notifications.py", line 26, in handle
    send_voting_session_notifications()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\tasks.py", line 34, in send_voting_session_notifications
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipients)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-43b7a28c6fesm952805e9.37 - gsmtp')
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 20:57:19.711357+00:00, Target time: 2025-02-26 21:57:19.711357+00:00
Found 1 sessions matching condition.
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\management\commands\send_notifications.py", line 26, in handle
    send_voting_session_notifications()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\tasks.py", line 34, in send_voting_session_notifications
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipients)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-43aba58713bsm34952345e9.34 - gsmtp')
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 21:02:20.219793+00:00, Target time: 2025-02-26 22:02:20.219793+00:00
Found 0 sessions matching condition.
\u2705 Notifications sent successfully!
Notifications sent!
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 21:07:20.790428+00:00, Target time: 2025-02-26 22:07:20.790428+00:00
Found 0 sessions matching condition.
\u2705 Notifications sent successfully!
Notifications sent!
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 21:12:19.440419+00:00, Target time: 2025-02-26 22:12:19.440419+00:00
Found 0 sessions matching condition.
\u2705 Notifications sent successfully!
Notifications sent!
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 21:17:20.529593+00:00, Target time: 2025-02-26 22:17:20.529593+00:00
Found 0 sessions matching condition.
\u2705 Notifications sent successfully!
Notifications sent!
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 21:22:19.563668+00:00, Target time: 2025-02-26 22:22:19.563668+00:00
Found 0 sessions matching condition.
\u2705 Notifications sent successfully!
Notifications sent!
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 21:23:04.483309+00:00, Target time: 2025-02-26 22:23:04.483309+00:00
Found 0 sessions matching condition.
\u2705 Notifications sent successfully!
Notifications sent!
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 21:26:38.574596+00:00, Target time: 2025-02-26 22:26:38.574596+00:00
Found 1 sessions matching condition.
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\management\commands\send_notifications.py", line 26, in handle
    send_voting_session_notifications()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\tasks.py", line 34, in send_voting_session_notifications
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipients)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-390e4795d1asm42502f8f.4 - gsmtp')
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 21:27:19.376546+00:00, Target time: 2025-02-26 22:27:19.376546+00:00
Found 1 sessions matching condition.
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\management\commands\send_notifications.py", line 26, in handle
    send_voting_session_notifications()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\tasks.py", line 34, in send_voting_session_notifications
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipients)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-43aba5710b7sm33664345e9.25 - gsmtp')
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 21:32:19.942521+00:00, Target time: 2025-02-26 22:32:19.942521+00:00
Found 1 sessions matching condition.
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\management\commands\send_notifications.py", line 26, in handle
    send_voting_session_notifications()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\tasks.py", line 34, in send_voting_session_notifications
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipients)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-43b73717171sm1884765e9.18 - gsmtp')
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 21:37:19.903472+00:00, Target time: 2025-02-26 22:37:19.903472+00:00
Found 1 sessions matching condition.
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\management\commands\send_notifications.py", line 26, in handle
    send_voting_session_notifications()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\tasks.py", line 34, in send_voting_session_notifications
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipients)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-390e47a6a5esm60472f8f.35 - gsmtp')
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 21:42:19.723622+00:00, Target time: 2025-02-26 22:42:19.723622+00:00
Found 1 sessions matching condition.
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\management\commands\send_notifications.py", line 26, in handle
    send_voting_session_notifications()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\tasks.py", line 34, in send_voting_session_notifications
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipients)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-390e484452asm49214f8f.61 - gsmtp')
Task started
\u2705 send_notifications.py started!
\U0001f4e7 Sending notifications...
Task completed successfully
Current time: 2025-02-26 21:47:22.398415+00:00, Target time: 2025-02-26 22:47:22.398415+00:00
Found 1 sessions matching condition.
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\management\commands\send_notifications.py", line 26, in handle
    send_voting_session_notifications()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\voting_sessions\tasks.py", line 34, in send_voting_session_notifications
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipients)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Володимир\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-390e46f580bsm100963f8f.0 - gsmtp')
\U0001f539 Task Scheduler triggered send_notifications.py
Current time: 2025-02-26 21:50:45.204978+00:00, Target time: 2025-02-26 22:50:45.204978+00:00
Found 0 sessions matching condition.
\u2705 Email notifications sent successfully
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 275, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 49, in load_command_class
    return module.Command()
AttributeError: module 'voting_sessions.management.commands.send_notifications' has no attribute 'Command'
\U0001f539 Task Scheduler triggered send_notifications.py
Current time: 2025-02-26 21:51:46.803279+00:00, Target time: 2025-02-26 22:51:46.803279+00:00
Found 1 sessions matching condition.
\u274c Error sending notifications: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-390e4844c0dsm64704f8f.80 - gsmtp')
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 275, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 49, in load_command_class
    return module.Command()
AttributeError: module 'voting_sessions.management.commands.send_notifications' has no attribute 'Command'
\U0001f539 Task Scheduler triggered send_notifications.py
Current time: 2025-02-26 21:52:20.538479+00:00, Target time: 2025-02-26 22:52:20.538479+00:00
Found 1 sessions matching condition.
\u274c Error sending notifications: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-390e47b7cdbsm84827f8f.54 - gsmtp')
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 275, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 49, in load_command_class
    return module.Command()
AttributeError: module 'voting_sessions.management.commands.send_notifications' has no attribute 'Command'
\U0001f539 Task Scheduler triggered send_notifications.py
Current time: 2025-02-26 21:53:16.939243+00:00, Target time: 2025-02-26 22:53:16.939243+00:00
Found 1 sessions matching condition.
\u274c Error sending notifications: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-390e47a72d5sm89245f8f.31 - gsmtp')
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 275, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 49, in load_command_class
    return module.Command()
AttributeError: module 'voting_sessions.management.commands.send_notifications' has no attribute 'Command'
\U0001f539 Task Scheduler triggered send_notifications.py
Current time: 2025-02-26 21:56:47.442003+00:00, Target time: 2025-02-26 22:56:47.442003+00:00
Found 1 sessions matching condition.
\u274c Error sending notifications: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-390e4847fe5sm75390f8f.73 - gsmtp')
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 275, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 49, in load_command_class
    return module.Command()
AttributeError: module 'voting_sessions.management.commands.send_notifications' has no attribute 'Command'
\U0001f539 Task Scheduler triggered send_notifications.py
Current time: 2025-02-26 21:57:19.871676+00:00, Target time: 2025-02-26 22:57:19.871676+00:00
Found 1 sessions matching condition.
\u274c Error sending notifications: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-390e47a6aabsm94437f8f.26 - gsmtp')
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 275, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 49, in load_command_class
    return module.Command()
AttributeError: module 'voting_sessions.management.commands.send_notifications' has no attribute 'Command'
Script started at Wed 02/26/2025 23:01:09.42 
\U0001f539 Task Scheduler triggered send_notifications.py
Current time: 2025-02-26 22:01:10.971713+00:00, Target time: 2025-02-26 23:01:10.971713+00:00
Found 1 sessions matching condition.
\u274c Error sending notifications: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-390e47b7c43sm100668f8f.49 - gsmtp')
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 275, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 49, in load_command_class
    return module.Command()
AttributeError: module 'voting_sessions.management.commands.send_notifications' has no attribute 'Command'
Script finished at Wed 02/26/2025 23:01:12.15 
Script started at Wed 02/26/2025 23:01:46.57 
\U0001f539 Task Scheduler triggered send_notifications.py
Current time: 2025-02-26 22:01:48.014023+00:00, Target time: 2025-02-26 23:01:48.014023+00:00
Found 1 sessions matching condition.
\u274c Error sending notifications: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-390e484451fsm85993f8f.63 - gsmtp')
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 275, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 49, in load_command_class
    return module.Command()
AttributeError: module 'voting_sessions.management.commands.send_notifications' has no attribute 'Command'
Script finished at Wed 02/26/2025 23:01:49.20 
Script started at Wed 02/26/2025 23:02:17.24 
\U0001f539 Task Scheduler triggered send_notifications.py
Current time: 2025-02-26 22:02:22.543653+00:00, Target time: 2025-02-26 23:02:22.543653+00:00
Found 1 sessions matching condition.
\u274c Error sending notifications: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-43aba52b6f3sm34036455e9.1 - gsmtp')
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 275, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 49, in load_command_class
    return module.Command()
AttributeError: module 'voting_sessions.management.commands.send_notifications' has no attribute 'Command'
Script finished at Wed 02/26/2025 23:02:23.89 
Script started at Wed 02/26/2025 23:06:53.66 
Running Python script... 
\U0001f539 Task Scheduler triggered send_notifications.py
Current time: 2025-02-26 22:06:55.238900+00:00, Target time: 2025-02-26 23:06:55.238900+00:00
Found 1 sessions matching condition.
\u274c Error sending notifications: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-390e485db82sm90652f8f.88 - gsmtp')
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 275, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 49, in load_command_class
    return module.Command()
AttributeError: module 'voting_sessions.management.commands.send_notifications' has no attribute 'Command'
Script finished at Wed 02/26/2025 23:06:56.50 
Script started at Wed 02/26/2025 23:07:17.32 
Running Python script... 
\U0001f539 Task Scheduler triggered send_notifications.py
Current time: 2025-02-26 22:07:19.085062+00:00, Target time: 2025-02-26 23:07:19.085062+00:00
Found 1 sessions matching condition.
\u274c Error sending notifications: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-390e47a6a4asm117652f8f.34 - gsmtp')
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 275, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 49, in load_command_class
    return module.Command()
AttributeError: module 'voting_sessions.management.commands.send_notifications' has no attribute 'Command'
Script finished at Wed 02/26/2025 23:07:20.22 
Script started at Wed 02/26/2025 23:12:17.52 
Running Python script... 
\U0001f539 Task Scheduler triggered send_notifications.py
Current time: 2025-02-26 22:12:20.601973+00:00, Target time: 2025-02-26 23:12:20.601973+00:00
Found 1 sessions matching condition.
\u274c Error sending notifications: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-390e485e61csm105164f8f.98 - gsmtp')
Email notification sent for session: Best Place
Traceback (most recent call last):
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 21, in <module>
    main()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 275, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\VS_Code\Camp_programs\Projects\vote_cast\venv\lib\site-packages\django\core\management\__init__.py", line 49, in load_command_class
    return module.Command()
AttributeError: module 'voting_sessions.management.commands.send_notifications' has no attribute 'Command'
Script finished at Wed 02/26/2025 23:12:21.96 
